import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import styles from './styles/style';
import './styles/globals.css';
import Nav from './components/Nav';
const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'S Kociuba - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundImage: "url('/images/background.jpg')",
        }}>
        <div className={styles.marginY}>
          {' '}
          <Nav />
        </div>
        {children}
      </body>
    </html>
  );
}
